### ISSUE TITLE
Revisar módulo 2 tema 2.3 ejercicio 1 v2.

### ISSUE THREAD

**Issue by EvaMarco** [Adalab/soluciones-alumnas-g#10]
https://github.com/Adalab/soluciones-alumnas-g/tree/m2-tema2.3-ej01-v2
@constanza-sosa ¿podrías revisar mi ejercicio?

**Comment by constanza-sosa** [comment]
hecho! puedes hacer merge :)

**Comment by EvaMarco** [comment]
Gracias Coco
