### ISSUE TITLE
 modulo1/s1.4/ej08

### ISSUE THREAD

**Issue by EvaMarco** [Adalab/soluciones-alumnas-g#4]
@patriciaSR Can you check my exercise? please

**Comment by patriciaSR** [comment]
Please, could you link your branch the next time? Something like "Ey! can you check my exercise branch [s1-4-e08](https://github.com/Adalab/soluciones-alumnas-g/tree/s1-4-e08/modulo1)?" will be awesome. 

Ok! I will review it ASAP :wink:

**Comment by EvaMarco** [comment]
Sure¡¡ Next time i'll do it.

**Comment by patriciaSR** [comment]
Well done!! 😃
Only some tips to the future:
1. `target="_blank"` attribute in `<a>` elements is only with one `_` not two.
2. Be carefull with class BEM naming, try to keep the order block__element--modifier. For example:
```html
article
  article__header
  article__title
  article__text
  article__text--blue
```
Even so, you did a really really good job!!!  💪

Go merge!!!!  🤘
