### ISSUE TITLE
mod2/s2.3/ej07-bonus-v2 

### ISSUE THREAD

**Issue by patriciaSR** [Adalab/soluciones-alumnas-g#9]
Ey @martagrio and @clarabrigido ! Can you check my exercise branch [s2.3-e07-bonus-v2](https://github.com/Adalab/soluciones-alumnas-g/tree/m2-s2.3-ej07-v2) please?

:smile_cat:

**Comment by martagrio** [comment]
Perfect. I give the green light to push it to the master. :frog:

**Comment by clarabrigido** [comment]
Great. It's good! 😃

**Comment by patriciaSR** [comment]
merge done!! :smiley:
